### PR TITLE
Now it compiles !

### PR DESCRIPTION
**Pull request by qtests**
Hi Sasa - as we talked, I added small corrections (ooh - the resolver is not important at all...) so that it compiles on my machine !

### CODE REVIEW

**Comment by qtests** [comment]
For the record - I have installed those libraries on ubuntu:
        sudo apt-get install libssl-dev
        sudo apt-get install libcurl4-gnutls-dev

**Comment by qtests** [comment]
Was even able to run and get the Hellow World

image

**Comment by qtests** [comment]
It works like a charm  -  take a look at the database/story table content :

image

**Comment by v0d1ch** [comment]
Good work!  :)

**Pull request merged**
